# Generated by Django 5.0.2 on 2025-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_period_start', models.DateField(db_index=True)),
                ('predicted_period_end', models.DateField()),
                ('predicted_ovulation_date', models.DateField(blank=True, null=True)),
                ('predicted_fertile_window_start', models.DateField(blank=True, null=True)),
                ('predicted_fertile_window_end', models.DateField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('algorithm_used', models.CharField(default='average', max_length=50)),
                ('based_on_cycles_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('actual_period_started', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Prediction',
                'verbose_name_plural': 'Cycle Predictions',
                'db_table': 'cycle_predictions',
                'ordering': ['-predicted_period_start'],
            },
        ),
        migrations.CreateModel(
            name='CycleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cycle_length', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shortest_cycle_length', models.IntegerField(default=0)),
                ('longest_cycle_length', models.IntegerField(default=0)),
                ('cycle_regularity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('average_period_length', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('shortest_period_length', models.IntegerField(default=0)),
                ('longest_period_length', models.IntegerField(default=0)),
                ('total_cycles_tracked', models.IntegerField(default=0)),
                ('complete_cycles_count', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cycle Statistics',
                'verbose_name_plural': 'Cycle Statistics',
                'db_table': 'cycle_statistics',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cycle', 'Cycle Pattern'), ('symptom', 'Symptom Pattern'), ('mood', 'Mood Pattern'), ('health', 'Health Recommendation'), ('general', 'General')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('generated_by', models.CharField(default='system', max_length=100)),
                ('based_on_data_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'db_table': 'insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
