# Generated by Django 5.0.2 on 2025-11-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cyclestatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cycleprediction',
            index=models.Index(fields=['user', '-predicted_period_start'], name='cycle_predi_user_id_b9bb44_idx'),
        ),
        migrations.AddIndex(
            model_name='cycleprediction',
            index=models.Index(fields=['user', 'is_active'], name='cycle_predi_user_id_85882a_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', '-created_at'], name='insights_user_id_5a13c1_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', 'is_read'], name='insights_user_id_5832b8_idx'),
        ),
    ]
