# Generated by Django 5.0.2 on 2025-11-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodday',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_days', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='daily_logs', to='cycles.symptom'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['user', '-start_date'], name='cycles_user_id_7a04a9_idx'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['user', 'is_active'], name='cycles_user_id_133638_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('user', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='periodday',
            index=models.Index(fields=['cycle', 'date'], name='period_days_cycle_i_4ea62c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodday',
            unique_together={('cycle', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['user', '-date'], name='daily_logs_user_id_7a3a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['cycle', 'date'], name='daily_logs_cycle_i_153497_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('user', 'date')},
        ),
    ]
